---
- name: Remove "ubuntu" user from "docker" group
  ansible.builtin.systemd_service:
    name: docker
    state: stopped
    enabled: false

- name: Remove Docker service
  ansible.builtin.systemd_service:
    name: docker
    state: stopped
    enabled: false

- name: Remove docker.io package
  ansible.builtin.apt:
    name: docker.io
    state: absent
    autoremove: true
    purge: true
