[project]
name = "rapture-minecraft-ansible"
version = "0.2.1"
description = "Easy self-hosted Minecraft server with Ansible."
authors = [
    {name = "Guilhem Santé", email = "guilhem.sante@kelps.org"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ansible>=13.7.0",
    "boto3>=1.43.19",
    "molecule>=26.4.0",
    "pytest>=9.0.3",
]
