[project]
name = "rapture-minecraft-ansible"
version = "0.2.0"
description = "Easy self-hosted Minecraft server with Ansible."
authors = [
    {name = "Guilhem Santé", email = "guilhem.sante@kelps.org"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ansible>=11.8.0",
    "boto3>=1.39.11",
    "docker-py>=1.10.6",
    "molecule>=25.6.0",
    "pytest>=8.4.1",
]
