---
name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  issues: read
  pull-requests: read

jobs:
  generate-changelog:
    name: Generate a changelog
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: CHANGES.md
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-publish:
    name: Publish release
    needs:
      - generate-changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ needs.generate-changelog.outputs.release_body }}
          draft: false
          prerelease: false
